# Generated by Django 5.2.5 on 2025-08-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
