# Generated by Django 5.2.5 on 2025-08-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order_updated_at_orderline_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
