# Generated by Django 5.2.5 on 2025-08-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_orderline_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
