# Generated by Django 5.2.5 on 2025-08-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_created_at_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availables',
            field=models.IntegerField(default=10),
        ),
    ]
