# Generated by Django 5.2.5 on 2025-08-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telesales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='number',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
    ]
