# Generated by Django 5.2.5 on 2025-08-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telesales', '0002_alter_salesorder_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
