# Generated by Django 5.2.5 on 2025-08-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telesales', '0003_reservation_updated_at_salesorder_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
