# Generated by Django 5.2.5 on 2025-08-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telesales', '0004_alter_reservation_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
