# Generated by Django 5.2.5 on 2025-08-28 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telesales', '0005_salesorder_vat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorder',
            old_name='vat',
            new_name='vat_rate',
        ),
    ]
