# Generated by Django 5.2.5 on 2025-08-28 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telesales', '0006_rename_vat_salesorder_vat_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='telesales.salesorder'),
        ),
    ]
