# Generated by Django 5.2.5 on 2025-08-28 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telesales', '0009_alter_reservation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='telesales.salesorder'),
        ),
    ]
